### PR TITLE
[Refactor] Fixed several issues after move to mono repo

### PR DESCRIPTION
**Pull request by RandellDawson**
This PR has the following items:

1. Introduces a couple of fixes to the sweeper script from issues right before the move to the mono repo.  These were related to moving labeler out of the root of the sweeper folder and placing into the pr-tasks sub-folder.

2. Combined two scripts which were being used to update the data manually on Glitch (pr-relations.glitch.me).  The new one-off script (get-pr-relations-data.js) downloads the current data.json and then pulls down applicable Github data which updates the data.json and automatically uploads it back to the Glitch server.

3. In an effort to use the same log file across all current one-off scripts and sweeper.js, the ProcessLog class was modified, so now every log created has the same JSON structure as is uploaded to the Glitch server.  This removed a lot of redundant code across 3 files.

4. During a pair-coding session with @honmanyau, we tweaked the UI for the Dashboard app to give it a more consistent look across all views.

5. Based on feedback from a couple of the moderators using the new Dashboard app, the PR title was added along with some other styling. 

6. Added some environment variables for running dashboard-api and dashboard-client in a development mode.

7.  Added a sample_data.json file as a starter file, so someone does not have to do a full data pull to get things up and running. 

8. Modified Pareto view to only display files with 2 or more PRs to speed up the report.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@honmanyau Please review the front-end and back-end code for the Dashboard app.

@raisedadead We will review all of this code in our next meeting.

**Comment by honmanyau** [comment]
@RandellDawson I have tested this locally using the latest copy of `data.json` and noticed that searching for filenames would cause an error to be thrown on the server because `username` is `undefined` on line 18 of `/dashboard-api/routes/search.js`. It appears that the committed version does not match that on the test server (fixed-healer). Titles are not being rendered when searching by PR numbers for similar reasons.

The app functioned as intended after updating `/dashboard-api/routes/search.js` and `/dashboard-api/routes/pr.js` to match those on the test server. I don't seem to be able to add commits to this for some reason, I'll leave that to you so that you can also confirm that these are indeed meant to be committed! :)

**Comment by RandellDawson** [comment]
@honmanyau Thanks for testing.  I will see what is going on with the issue for searching for filenames.

**Comment by RandellDawson** [comment]
@honmanyau I believe I have fixed the problems you indicated.  I tested locally and it all seems good now.

**Review by raisedadead — APPROVED** [review]
This LGTM! We are just waiting on the fix for Pareto before our public release.

**Comment by RandellDawson** [comment]
@raisedadead Alright, it was something very simple.  It is fixed.  Feel free to test it.  Once you merge this PR, I will update the pr-relations.glitch.me site with the dashboard-api.  If you could pull down the merged master to the Digital Ocean server and set up the cron job to run `get-pr-relations-data.js` script located in the `sweeper/one-off-scripts` directory to run every 15 minutes, that would be great.  Because of something I have not figured out yet regarding dotenv library, you must run the `get-pr-relations-data.js` script for sweeper and not the root directory.

**Pull request merged**
